steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/truculentbanter/github.com/entropydown/notelearn:master", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/truculentbanter/github.com/entropydown/notelearn:master"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/notelearn-production'
  - '--namespace=production'
  - 'notelearn-sha256=gcr.io/truculentbanter/github.com/entropydown/notelearn:master'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=notelearn-cluster-production'
